version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.13.1
    steps:
      - checkout
      - run:
          name: Install Node Packages
          command: npm install
      - run:
          name: Install Angular
          command: echo y | sudo npm install -g @angular/cli
      - run:
          name: Build Angular Application
          command: ng build --prod
      - sonarcloud/scan
  deploy:
    docker:
      - image: circleci/node:12.13.1
    # working_directory: ~/circleci-docs
    steps:
      - run:
          name: Install awscli
          command: sudo npm install awscli
      - run:
          name: Deploy to S3
          command: aws s3 sync dist/rideshare-frontend s3://rideshare-frontend --delete

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
      - deploy:
          # requires:
          #   - build
          filters:
            branches:
              only: circleci-integration



